version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/config:/config
    network_mode: bridge
    ports:
      - 8006:80
      - 406:443
    restart: unless-stopped
  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/media/movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
  plex:
    container_name: plex
    restart: unless-stopped
    image: linuxserver/plex
    network_mode: host
    volumes:
      - ${USERDIR}/docker/plex:/config
      - /mnt/storage/downloads/plex_tmp:/transcode
      - /mnt/storage/media/movies:/movies
      - /mnt/storage/media/tv:/tv
      - /mnt/storage/media/audio/music:/music
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
      - HOSTNAME=Docker Plex
      - PLEX_CLAIM="claim-ID"
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ADVERTISE_IP=http://192.168.1.72:32400/
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - /mnt/storage/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 9117:9117
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - 9092:9091
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission-vpn:/data
      - ${USERDIR}/docker/shared:/shared
      - /mnt/storage/downloads:/data/watch
      - /mnt/storage/downloads:/data/completed
      - /mnt/storage/downloads/incomplete:/data/incomplete
      - /home/specter/docker/transmission-vpn/default.ovpn:/etc/openvpn/custom/default.ovpn
    environment:
      - OPENVPN_PROVIDER=CUSTOM
      - OPENVPN_USERNAME=dummy
      - OPENVPN_PASSWORD=dummy
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_RPC_HOST_WHITELIST=127.0.0.1,192.168.1.1,192.168.1.75
      - TRANSMISSION_RPC_PASSWORD=PASSWORD
      - TRANSMISSION_RPC_USERNAME=USERNAME
      - TRANSMISSION_UMASK=0
      - TRANSMISSION_RATIO_LIMIT=1.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - WEBPROXY_ENABLED=true
      - TRANSMISSION_WEB_UI=combustion
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/duplicati:/config
      - /mnt/storage/backups:/backups
      - /media:/source
    ports:
      - 8200:8200
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/media/tv:/tv
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/shared:/shared
    ports:
      - 8989:8989
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
  soulseek:
    image: realies/soulseek
    container_name: soulseek
    volumes:
      - ${USERDIR}/docker/soulseek:/data/.SoulseekQt
      - /mnt/storage/downloads/music:/data/Soulseek Downloads
      - ${USERDIR}/docker/soulseek/logs:/data/Soulseek Chat Logs
      - /mnt/storage/media/audio/music:/data/Music
    ports:
      - 6080:6080
    environment:
      - PUID=1000
      - PGID=1000
      - resize=scale
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: 'PASSWORD'
    volumes:
      - '${USERDIR}/docker/etc-pihole/:/etc/pihole/'
      - '${USERDIR}/docker/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
    restart: unless-stopped
  deemix:
    container_name: Deemix
    image: registry.gitlab.com/bockiii/deemix-docker
    restart: unless-stopped
    ports:
      - 6595:6595
    environment:
      - PUID=1000
      - PGID=1000
      - ARL=${ARL}
    volumes:
      - /mnt/storage/downloads/music:/downloads
      - ${USERDIR}/docker/deemix:/config
  beets:
    image: linuxserver/beets
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ= ${TZ}
    volumes:
      - ${USERDIR}/docker/beets/:/config
      - /mnt/storage/media/audio/music/:/music
      - /mnt/storage/downloads/music/:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped
