= Project Background

Coming to this doc site, you might find yourself asking, "Why a home server?" and "Why not a cloud service?" The truth is,
I initially started this project as a way for me to learn new technologies, tools, and systems. Since that time, the project 
scope has grown---up to and including this separate documentation project.

== "Why a home server?"

To learn...

- Linux system administration
- Network infrastructure and security
- File system optimization, structure, and archival processes
- Data management, redundancies, and backups
- Home automation and the IOT landscape
- Docs-as-code methodology

Essentially, to regain control over my data where I can, and to provide a "hub" that I can access securely from anywhere.

So far it has been an interesting challenge and provided me _a lot_ of useful and transferable skills for the IT industry. 

== "Why not a cloud service?"

While the startup costs can greatly outweight a yearly subscription to, say, a service for data backups or media streaming, 
I know once established, this approach will be able to grow with my needs. Most importantly, I know my data and personal 
information is secure and that I have the final say in what is done with this information.

=== This home server project needs to fulfill the following roles:

1. Provide reliable file storage and backups for multiple machines and users.
2. Create a media hub for a large, converted, digital media library.
3. Include a space for personal documentation and note collection.footnote:[Obviously my personal documentation for the home server build outgrew the server itself and information is now hosted externally through this site.]

=== Plans for the future

* [ ] Create home network DNS and ad blocking with https://pi-hole.net/[Pi-hole] or https://adguard.com/en/welcome.html[AdGuard].
* [ ] Home automation and metric collections using https://www.home-assistant.io/hassio/[Hass.io] and various IOT sensors and devices.
* [ ] Add two more disks to the pool and implement an offsite backup for critical cold storage.
* [ ] Add a Raspberry Pi for Pi-hole, https://networkupstools.org/[Network UPS] monitoring, and system monitoring.
* [ ] Use an old Android phone as a home controller.  

TIP: I hope you find the information you're looking for, or at the very least feel inspired to create your own home server. 
Good luck, from all of us at SpecterLab.
